/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DebuggerRouteImport } from './routes/debugger'
import { Route as LightingRouteImport } from './routes/lighting'
import { Route as LightsRouteImport } from './routes/lights'
import { Route as MaterialsRouteImport } from './routes/materials'
import { Route as MoveCameraRouteImport } from './routes/move-camera'
import { Route as PathsRouteImport } from './routes/paths'
import { Route as ScreenResizeRouteImport } from './routes/screen-resize'
import { Route as ShapesRouteImport } from './routes/shapes'
import { Route as SidesRouteImport } from './routes/sides'
import { Route as SimpleRendererRouteImport } from './routes/simple-renderer'
import { Route as TexturesRouteImport } from './routes/textures'
import { Route as UiDebuggerRouteImport } from './routes/ui-debugger'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DebuggerRoute = DebuggerRouteImport.update({
  id: '/debugger',
  path: '/debugger',
  getParentRoute: () => rootRouteImport,
} as any)
const LightingRoute = LightingRouteImport.update({
  id: '/lighting',
  path: '/lighting',
  getParentRoute: () => rootRouteImport,
} as any)
const LightsRoute = LightsRouteImport.update({
  id: '/lights',
  path: '/lights',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialsRoute = MaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => rootRouteImport,
} as any)
const MoveCameraRoute = MoveCameraRouteImport.update({
  id: '/move-camera',
  path: '/move-camera',
  getParentRoute: () => rootRouteImport,
} as any)
const PathsRoute = PathsRouteImport.update({
  id: '/paths',
  path: '/paths',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreenResizeRoute = ScreenResizeRouteImport.update({
  id: '/screen-resize',
  path: '/screen-resize',
  getParentRoute: () => rootRouteImport,
} as any)
const ShapesRoute = ShapesRouteImport.update({
  id: '/shapes',
  path: '/shapes',
  getParentRoute: () => rootRouteImport,
} as any)
const SidesRoute = SidesRouteImport.update({
  id: '/sides',
  path: '/sides',
  getParentRoute: () => rootRouteImport,
} as any)
const SimpleRendererRoute = SimpleRendererRouteImport.update({
  id: '/simple-renderer',
  path: '/simple-renderer',
  getParentRoute: () => rootRouteImport,
} as any)
const TexturesRoute = TexturesRouteImport.update({
  id: '/textures',
  path: '/textures',
  getParentRoute: () => rootRouteImport,
} as any)
const UiDebuggerRoute = UiDebuggerRouteImport.update({
  id: '/ui-debugger',
  path: '/ui-debugger',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/debugger': typeof DebuggerRoute
  '/lighting': typeof LightingRoute
  '/lights': typeof LightsRoute
  '/materials': typeof MaterialsRoute
  '/move-camera': typeof MoveCameraRoute
  '/paths': typeof PathsRoute
  '/screen-resize': typeof ScreenResizeRoute
  '/shapes': typeof ShapesRoute
  '/sides': typeof SidesRoute
  '/simple-renderer': typeof SimpleRendererRoute
  '/textures': typeof TexturesRoute
  '/ui-debugger': typeof UiDebuggerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/debugger': typeof DebuggerRoute
  '/lighting': typeof LightingRoute
  '/lights': typeof LightsRoute
  '/materials': typeof MaterialsRoute
  '/move-camera': typeof MoveCameraRoute
  '/paths': typeof PathsRoute
  '/screen-resize': typeof ScreenResizeRoute
  '/shapes': typeof ShapesRoute
  '/sides': typeof SidesRoute
  '/simple-renderer': typeof SimpleRendererRoute
  '/textures': typeof TexturesRoute
  '/ui-debugger': typeof UiDebuggerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/debugger': typeof DebuggerRoute
  '/lighting': typeof LightingRoute
  '/lights': typeof LightsRoute
  '/materials': typeof MaterialsRoute
  '/move-camera': typeof MoveCameraRoute
  '/paths': typeof PathsRoute
  '/screen-resize': typeof ScreenResizeRoute
  '/shapes': typeof ShapesRoute
  '/sides': typeof SidesRoute
  '/simple-renderer': typeof SimpleRendererRoute
  '/textures': typeof TexturesRoute
  '/ui-debugger': typeof UiDebuggerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/debugger'
    | '/lighting'
    | '/lights'
    | '/materials'
    | '/move-camera'
    | '/paths'
    | '/screen-resize'
    | '/shapes'
    | '/sides'
    | '/simple-renderer'
    | '/textures'
    | '/ui-debugger'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/debugger'
    | '/lighting'
    | '/lights'
    | '/materials'
    | '/move-camera'
    | '/paths'
    | '/screen-resize'
    | '/shapes'
    | '/sides'
    | '/simple-renderer'
    | '/textures'
    | '/ui-debugger'
  id:
    | '__root__'
    | '/'
    | '/debugger'
    | '/lighting'
    | '/lights'
    | '/materials'
    | '/move-camera'
    | '/paths'
    | '/screen-resize'
    | '/shapes'
    | '/sides'
    | '/simple-renderer'
    | '/textures'
    | '/ui-debugger'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DebuggerRoute: typeof DebuggerRoute
  LightingRoute: typeof LightingRoute
  LightsRoute: typeof LightsRoute
  MaterialsRoute: typeof MaterialsRoute
  MoveCameraRoute: typeof MoveCameraRoute
  PathsRoute: typeof PathsRoute
  ScreenResizeRoute: typeof ScreenResizeRoute
  ShapesRoute: typeof ShapesRoute
  SidesRoute: typeof SidesRoute
  SimpleRendererRoute: typeof SimpleRendererRoute
  TexturesRoute: typeof TexturesRoute
  UiDebuggerRoute: typeof UiDebuggerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debugger': {
      id: '/debugger'
      path: '/debugger'
      fullPath: '/debugger'
      preLoaderRoute: typeof DebuggerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lighting': {
      id: '/lighting'
      path: '/lighting'
      fullPath: '/lighting'
      preLoaderRoute: typeof LightingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lights': {
      id: '/lights'
      path: '/lights'
      fullPath: '/lights'
      preLoaderRoute: typeof LightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materials': {
      id: '/materials'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof MaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/move-camera': {
      id: '/move-camera'
      path: '/move-camera'
      fullPath: '/move-camera'
      preLoaderRoute: typeof MoveCameraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paths': {
      id: '/paths'
      path: '/paths'
      fullPath: '/paths'
      preLoaderRoute: typeof PathsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screen-resize': {
      id: '/screen-resize'
      path: '/screen-resize'
      fullPath: '/screen-resize'
      preLoaderRoute: typeof ScreenResizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shapes': {
      id: '/shapes'
      path: '/shapes'
      fullPath: '/shapes'
      preLoaderRoute: typeof ShapesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sides': {
      id: '/sides'
      path: '/sides'
      fullPath: '/sides'
      preLoaderRoute: typeof SidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simple-renderer': {
      id: '/simple-renderer'
      path: '/simple-renderer'
      fullPath: '/simple-renderer'
      preLoaderRoute: typeof SimpleRendererRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/textures': {
      id: '/textures'
      path: '/textures'
      fullPath: '/textures'
      preLoaderRoute: typeof TexturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui-debugger': {
      id: '/ui-debugger'
      path: '/ui-debugger'
      fullPath: '/ui-debugger'
      preLoaderRoute: typeof UiDebuggerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DebuggerRoute: DebuggerRoute,
  LightingRoute: LightingRoute,
  LightsRoute: LightsRoute,
  MaterialsRoute: MaterialsRoute,
  MoveCameraRoute: MoveCameraRoute,
  PathsRoute: PathsRoute,
  ScreenResizeRoute: ScreenResizeRoute,
  ShapesRoute: ShapesRoute,
  SidesRoute: SidesRoute,
  SimpleRendererRoute: SimpleRendererRoute,
  TexturesRoute: TexturesRoute,
  UiDebuggerRoute: UiDebuggerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
