/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DebuggerRouteImport } from './routes/debugger'
import { Route as LightingRouteImport } from './routes/lighting'
import { Route as ShapesRouteImport } from './routes/shapes'
import { Route as SimpleRendererRouteImport } from './routes/simple-renderer'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DebuggerRoute = DebuggerRouteImport.update({
  id: '/debugger',
  path: '/debugger',
  getParentRoute: () => rootRouteImport,
} as any)
const LightingRoute = LightingRouteImport.update({
  id: '/lighting',
  path: '/lighting',
  getParentRoute: () => rootRouteImport,
} as any)
const ShapesRoute = ShapesRouteImport.update({
  id: '/shapes',
  path: '/shapes',
  getParentRoute: () => rootRouteImport,
} as any)
const SimpleRendererRoute = SimpleRendererRouteImport.update({
  id: '/simple-renderer',
  path: '/simple-renderer',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/debugger': typeof DebuggerRoute
  '/lighting': typeof LightingRoute
  '/shapes': typeof ShapesRoute
  '/simple-renderer': typeof SimpleRendererRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/debugger': typeof DebuggerRoute
  '/lighting': typeof LightingRoute
  '/shapes': typeof ShapesRoute
  '/simple-renderer': typeof SimpleRendererRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/debugger': typeof DebuggerRoute
  '/lighting': typeof LightingRoute
  '/shapes': typeof ShapesRoute
  '/simple-renderer': typeof SimpleRendererRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/debugger' | '/lighting' | '/shapes' | '/simple-renderer'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/debugger' | '/lighting' | '/shapes' | '/simple-renderer'
  id:
    | '__root__'
    | '/'
    | '/debugger'
    | '/lighting'
    | '/shapes'
    | '/simple-renderer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DebuggerRoute: typeof DebuggerRoute
  LightingRoute: typeof LightingRoute
  ShapesRoute: typeof ShapesRoute
  SimpleRendererRoute: typeof SimpleRendererRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debugger': {
      id: '/debugger'
      path: '/debugger'
      fullPath: '/debugger'
      preLoaderRoute: typeof DebuggerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lighting': {
      id: '/lighting'
      path: '/lighting'
      fullPath: '/lighting'
      preLoaderRoute: typeof LightingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shapes': {
      id: '/shapes'
      path: '/shapes'
      fullPath: '/shapes'
      preLoaderRoute: typeof ShapesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simple-renderer': {
      id: '/simple-renderer'
      path: '/simple-renderer'
      fullPath: '/simple-renderer'
      preLoaderRoute: typeof SimpleRendererRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DebuggerRoute: DebuggerRoute,
  LightingRoute: LightingRoute,
  ShapesRoute: ShapesRoute,
  SimpleRendererRoute: SimpleRendererRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
